// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Matias Nuñez",
            "url": "http://www.swagger.io/support",
            "email": "matiasne45@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/items": {
            "get": {
                "description": "Get Items by User ID in headers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get Items by User ID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ItemsOutput"
                        }
                    }
                }
            },
            "post": {
                "description": "Create item in db",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Create Item",
                "parameters": [
                    {
                        "description": "Add item",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ItemDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    }
                }
            }
        },
        "/items/list": {
            "post": {
                "description": "Get item by IDs in body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get items by ids",
                "parameters": [
                    {
                        "description": "Add items",
                        "name": "items",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.ItemsIds"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ItemsOutput"
                        }
                    }
                }
            }
        },
        "/items/shop/{id}": {
            "get": {
                "description": "Get details of items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get details of items by shop ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shop ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ItemsOutput"
                        }
                    }
                }
            }
        },
        "/items/shop/{id}/category/{category_id}": {
            "get": {
                "description": "Get details of items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get details of items by shop ID and category ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shop ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ItemsOutput"
                        }
                    }
                }
            }
        },
        "/items/{id}": {
            "get": {
                "description": "Get details of item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get details of item id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Item"
                        }
                    }
                }
            },
            "put": {
                "description": "Update item by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Update item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add item",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ItemDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete item by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Delete item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "test if the router works correctly",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Attributes": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "domain.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Currency": {
            "type": "object",
            "properties": {
                "decimal_divider": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "thousands_divider": {
                    "type": "string"
                }
            }
        },
        "domain.Eligible": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_required": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.Item": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/domain.Attributes"
                },
                "category": {
                    "$ref": "#/definitions/domain.Category"
                },
                "description": {
                    "type": "string"
                },
                "eligible": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Eligible"
                    }
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "$ref": "#/definitions/domain.Price"
                },
                "shop_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "default": "active"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.ItemsIds": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.ItemsOutput": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Item"
                    }
                }
            }
        },
        "domain.Price": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "$ref": "#/definitions/domain.Currency"
                }
            }
        },
        "dto.AttributesDTO": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "dto.CategoryDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CurrencyDTO": {
            "type": "object",
            "properties": {
                "decimal_divider": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "thousands_divider": {
                    "type": "string"
                }
            }
        },
        "dto.EligibleDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_required": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ItemDTO": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/dto.AttributesDTO"
                },
                "category": {
                    "$ref": "#/definitions/dto.CategoryDTO"
                },
                "description": {
                    "type": "string"
                },
                "eligible": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.EligibleDTO"
                    }
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "$ref": "#/definitions/dto.PriceDTO"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.PriceDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "$ref": "#/definitions/dto.CurrencyDTO"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Jopit API Items",
	Description:      "This is a jopit api items.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
